### ISSUE TITLE
Can't run on 1.21.1 server

### ISSUE THREAD

**Issue by wibucter** [Ramixin/SlashLength#2]
i can't run it in 1.21.1 fabric server, it doesn't detect mod in the log
![ảnh](https://github.com/user-attachments/assets/c1ab83b7-136c-4212-9970-5e256d3cc0d1)

**Comment by Ramixin** [comment]
@wibucter , thanks for reaching out.  To help me, could you please create a link for the log with https://mclo.gs? I would like to make sure since Slash Length is technically not the name of the mod (the ID is No Chat Length Limit, or NCCL)

**Comment by Ramixin** [comment]
After a second thought, I realized you meant an actual server and not the internal server used to run singleplayer. Slash Length is a client-side mod and will not be detected by the server to not waste any time doing so. All changes made by the mod are independent of the server.
